name = "MyAwesomePackage"
uuid = "13b504ee-4fd6-44c9-bf49-d644c72af026"
authors = ["SwampratMPH"]
version = "0.0.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DataFrames = "1.7.0, 1.8.0"
LinearAlgebra = "1.11.0"
julia = "1.11.2"

